# Generated by Django 6.1 on 2026-08-18 16:27

import django.db.models.deletion
import django_event_bus.remote.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', django_event_bus.remote.fields.RemoteForeignKey(accessor_name=None, db_index=True, invalidate_on=('orders.order_updated',), resource='orders', service='service_order', transport=None, ttl=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
