# Generated by Django 6.1 on 2026-08-18 13:33

import django_event_bus.remote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64)),
                ('user_id', django_event_bus.remote.fields.RemoteForeignKey(accessor_name=None, db_index=True, invalidate_on=('auth.user_updated',), resource='users', service='service_auth', transport=None, ttl=None)),
            ],
        ),
    ]
